import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar.component";
import { QueryClientProvider } from "@/components/wrappers/queryClient/queryClient.wrapper";
import { ToasterProvider } from "@/components/wrappers/toast/toast.wrapper";
import { ThemeProvider } from "@/components/wrappers/nextTheme/nextTheme.wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <QueryClientProvider>
          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>
          <ToasterProvider />
        </QueryClientProvider>
      </body>
    </html>
  );
}
